-- DEPARTMENTS 테이블에서 DEPARTMENT_NAME 이 Marketing인 데이터 조회
SELECT * 
FROM DEPARTMENTS 
WHERE DEPARTMENT_NAME = 'Marketing';


-- DEPARTMENTS 테이블에서 DEPARTMENT_NAME에 IT가 포함된 데이터 조회
SELECT * 
FROM DEPARTMENTS 
 WHERE DEPARTMENT_NAME LIKE '%IT%';


-- LOCATIONS 테이블에서 COUNTRY_ID가 US인 데이터 조회할 때
-- STREET_ADDRESS, POSTAL_CODE, CITY 컬럼만 조회한다.
SELECT STREET_ADDRESS 
	 , POSTAL_CODE
	 , CITY
  FROM LOCATIONS 
 WHERE COUNTRY_ID = 'US';


-- LOCATIONS 테이블에서 POSTAL_CODE가 5자리인 데이터 조회
SELECT * FROM LOCATIONS WHERE POSTAL_CODE LIKE '_____';

-- EMPLOYEES 테이블에서 MANAGER_ID가 100이고 DEPARTMENT_ID가 50인 데이터 조회
SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID = 100
AND DEPARTMENT_ID = 50;

-- EMPLOYEES 테이블에서 COMMISSION_PCT가 NULL이 아니면서 SALARY가 1000이상인
-- 데이터를 조회 할 때 COMMISSION_PCT가 포함된 급여로 조회
-- SALARY, COMMISSION_PCT, TOTAL,SALARY 컬럼명으로 결과가 나오게 한다.
SELECT SALARY 
     , COMMISSION_PCT 
     , SALARY * (1 + COMMISSION_PCT) AS TOTAL_SALARY
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL 
AND SALARY >= 10000;


-- EMPLOYEES 테이블에서 MANAGER_ID가 100, 101, 102, 200, 201, 202인 데이터 조회
-- FIRST_NAME, LAST_NAME은 하나의 컬럼(EMP_NAME)으로 조회되도록 한다.
SELECT EMPLOYEE_ID 
     , FIRST_NAME || ' ' || LAST_NAME AS EMP_NAME
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
FROM EMPLOYEES
WHERE MANAGER_ID IN(100, 101, 102, 200, 201, 202)

-- EMPLOYEES 테이블에서 EMAIL 컬럼을 조회할 때 EMAIL@JOB_ID.employee.com 형식으로 조회
-- 되도록 한다.
-- 예) EMPLOYEE_ID가 100인 사원은 EMAIL이 SKING JOB_ID가 AD_PRES이다. 이를 문제에서
-- 제시하는 형식으로 조회하면 SKING@AD_PRES.employee.com으로 조회가 된다.
SELECT EMAIL || '@' || JOB_ID || '.employee.com' AS EMAIL 
FROM EMPLOYEES;