/*
 * HR 데이터 정보 확인
 */

-- 직원 테이블
SELECT * FROM EMPLOYEES;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES; 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID = 100; 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID > 100; 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID != 100;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID <> 100; 

-- 부서 테이블
SELECT * FROM DEPARTMENTS;

-- 국가 테이블
SELECT * FROM COUNTRIES;

-- 국가의 지역 테이블
SELECT * FROM LOCATIONS;

-- 직급 테이블
SELECT * FROM JOBS;

--대륙 정보 테이블
SELECT * FROM REGIONS;


-- 컬럼명에 별칭 부여
SELECT EMPLOYEE_ID AS "사번"
	, FIRST_NAME "이름" 
	, LAST_NAME 성
	, EMAIL "이메일 주소"
	FROM EMPLOYEES;

-- 컬럼과의 연산(문자열 연산, 곱셈 연산)
SELECT EMPLOYEE_ID "사번"
	, LAST_NAME || ' ' || FIRST_NAME "성명"
	, SALARY * 12 || '달러' "연봉"
	FROM EMPLOYEES;

-- 조건절
SELECT EMPLOYEE_ID "사번"
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID > 200;
 
-- 조건절에서 사용하는 연산자
-- AND, OR, IN, NOT, NOT IN, BETWEEN ... AND, LIKE
-- IS NULL, IS NOT NULL
SELECT * FROM EMPLOYEES
 WHERE EMPLOYEE_ID > 200
   AND SALARY >= 10000;
   

SELECT * FROM EMPLOYEES
 WHERE EMPLOYEE_ID > 200
   OR  SALARY >= 10000;
  
SELECT * FROM EMPLOYEES
 WHERE NOT EMPLOYEE_ID > 200;
 
SELECT * FROM EMPLOYEES
 WHERE NOT EMPLOYEE_ID > 200
   AND SALARY >= 10000;

SELECT * FROM EMPLOYEES
 WHERE EMPLOYEE_ID IN (200, 201, 202, 203); 

SELECT * FROM EMPLOYEES
 WHERE EMPLOYEE_ID NOT IN (200, 201, 202, 203); 

SELECT * FROM EMPLOYEES
 WHERE EMPLOYEE_ID BETWEEN 200 AND 203;

SELECT * FROM EMPLOYEES
 WHERE EMPLOYEE_ID NOT BETWEEN 200 AND 203;

SELECT * FROM EMPLOYEES
 WHERE JOB_ID LIKE 'AD%'; -- 문자열에서 와일드카드(%)를 사용하여 원하는 문자가 포함된 자료를 쉽게 검색할 수 있다.
 
 SELECT * FROM EMPLOYEES
 WHERE JOB_ID LIKE '%AP';
 
SELECT * FROM EMPLOYEES
 WHERE JOB_ID LIKE '%A%';
 
SELECT * FROM EMPLOYEES
 WHERE PHONE_NUMBER LIKE '___.127.____'; -- 언더바(_)를 사용하여 검색할 문자열의 자릿수를 결정하여 검색이 가능하다.

-- ESCAPE로 지정하여 바로 앞 텍스트와 함께 묶어서 사용하기
SELECT * FROM EMPLOYEES
 WHERE JOB_ID LIKE '%#____' ESCAPE '#';

SELECT * FROM EMPLOYEES
 WHERE JOB_ID LIKE '%\____' ESCAPE '\';
 
SELECT EMPLOYEE_ID
	,  FIRST_NAME
	,  LAST_NAME
	,  COMMISSION_PCT
 FROM  EMPLOYEES
WHERE  COMMISSION_PCT IS NULL; 

SELECT EMPLOYEE_ID
	,  FIRST_NAME
	,  LAST_NAME
	,  COMMISSION_PCT
 FROM  EMPLOYEES
WHERE  COMMISSION_PCT IS NOT NULL; 

-- 사용할 수 없는 연산자
--SELECT EMPLOYEE_ID
--	,  FIRST_NAME
--	,  LAST_NAME
--	,  COMMISSION_PCT
-- FROM  EMPLOYEES
--WHERE  COMMISSION_PCT (<>,!=,=) NULL;
--NULL은 반드시 'IS NULL' 혹은 'IS NOT NULL'으로만 사용할 수 있다.