/*
 * HR 데이터 정보 확인
 */

-- 직원 테이블
SELECT * FROM EMPLOYEES;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES; 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID = 100; 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID > 100; 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID != 100;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID <> 100; 

-- 부서 테이블
SELECT * FROM DEPARTMENTS;

-- 국가 테이블
SELECT * FROM COUNTRIES;

-- 국가의 지역 테이블
SELECT * FROM LOCATIONS;

-- 직급 테이블
SELECT * FROM JOBS;

--대륙 정보 테이블
SELECT * FROM REGIONS;
