SELECT *
  FROM EMPLOYEES, DEPARTMENTS;
-- WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

 SELECT *
  FROM DEPARTMENTS, EMPLOYEES;
 

SELECT *
  FROM EMPLOYEES
  JOIN DEPARTMENTS
 USING(DEPARTMENT_ID);

SELECT *
  FROM EMPLOYEES
  JOIN DEPARTMENTS
    ON (EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID);

SELECT *
  FROM EMPLOYEES
  LEFT JOIN DEPARTMENTS
 USING(DEPARTMENT_ID)
 WHERE EMPLOYEE_ID = 178;

SELECT *
  FROM EMPLOYEES
 RIGHT JOIN DEPARTMENTS
 USING(DEPARTMENT_ID);

SELECT *
  FROM EMPLOYEES
  FULL JOIN DEPARTMENTS
 USING(DEPARTMENT_ID);


SELECT *
  FROM EMPLOYEES E
  JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
 WHERE E.COMMISSION_PCT IS NOT NULL
   AND D.DEPARTMENT_ID = 80;


  
  
SELECT COUNT(*)
  FROM EMPLOYEES E
 CROSS JOIN DEPARTMENTS D;

SELECT X, Y
     , (X * Y)
  FROM (SELECT (SELECT COUNT(*) FROM EMPLOYEES) AS X
             , (SELECT COUNT(*) FROM DEPARTMENTS) AS Y
          FROM DUAL);


SELECT E.EMPLOYEE_ID
     , E.FIRST_NAME || ' ' || E.LAST_NAME
     , E.JOB_ID
     , J.JOB_ID
     , J.JOB_TITLE
     , E.SALARY
     , J.MIN_SALARY
     , J.MAX_SALARY
  FROM EMPLOYEES E
  JOIN JOBS J
    ON E.SALARY BETWEEN J.MIN_SALARY AND J.MAX_SALARY
   AND E.JOB_ID = J.JOB_ID
 ORDER BY 1;


SELECT E1.EMPLOYEE_ID
     , E1.FIRST_NAME || ' ' || E1.LAST_NAME
     , E2.EMPLOYEE_ID
     , E2.FIRST_NAME || ' ' || E2.LAST_NAME
     , E2.MANAGER_ID
  FROM EMPLOYEES E1
  JOIN EMPLOYEES E2
    ON E1.EMPLOYEE_ID = E2.MANAGER_ID;


SELECT E.EMPLOYEE_ID
     , E.FIRST_NAME
     , E.LAST_NAME
     , E.EMAIL
     , E.PHONE_NUMBER
     , E.HIRE_DATE
     , J.JOB_TITLE
     , E.SALARY
     , E.COMMISSION_PCT
     , E.MANAGER_ID
     , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
  JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
  JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;SELECT E.EMPLOYEE_ID
     , E.FIRST_NAME
     , E.LAST_NAME
     , E.EMAIL
     , E.PHONE_NUMBER
     , E.HIRE_DATE
     , J.JOB_TITLE
     , E.SALARY
     , E.COMMISSION_PCT
     , E.MANAGER_ID
     , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
  JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
  JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;SELECT E.EMPLOYEE_ID
     , E.FIRST_NAME
     , E.LAST_NAME
     , E.EMAIL
     , E.PHONE_NUMBER
     , E.HIRE_DATE
     , J.JOB_TITLE
     , E.SALARY
     , E.COMMISSION_PCT
     , E.MANAGER_ID
     , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
  JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
  JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;SELECT E.EMPLOYEE_ID
     , E.FIRST_NAME
     , E.LAST_NAME
     , E.EMAIL
     , E.PHONE_NUMBER
     , E.HIRE_DATE
     , J.JOB_TITLE
     , E.SALARY
     , E.COMMISSION_PCT
     , E.MANAGER_ID
     , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
  JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
  JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
















