/*
 * DDL
 *     - Data Definition Language : 데이터 정의어
 *     - 객체를 정의하기 위한 CREATE(생성), ALTER(수정), DROP(삭제) 구문이 있다.
 *     - 오라클 객체는 TABLE, VIEW, SEQUENCE, FUNCTION, PROCEDUAL, USER, .... 등이 있다.
 */

/*
 * CREATE TABLE 테이블명 (
 *     컬럼명 자료형(크기) [제약조건]
 *   , ...
 * );
 */

CREATE TABLE sample_t (
       u_id      NUMBER       -- PRIMARY KEY
     , jumin     CHAR(13)     -- UNIQUE
     , name      VARCHAR2(50) NOT NULL
     , age       NUMBER(3)    DEFAULT(0)
     , gender    CHAR(1)      CHECK(GENDER IN ('M', 'F'))
     , birth_day DATE         DEFAULT(SYSDATE)
     , ref_col   NUMBER       -- REFERENCES ref_t(r_id)
     , CONSTRAINT PK_U_ID PRIMARY KEY(u_id)
     , CONSTRAINT UK_JUMIN UNIQUE(jumin)
     , CONSTRAINT FK_REF_T_R_ID FOREIGN KEY(ref_col) REFERENCES ref_t(r_id)
);
CREATE TABLE ref_t (
       r_id NUMBER PRIMARY KEY
     , note VARCHAR2(100)
);
DROP TABLE sample_t;
DROP TABLE ref_t;

COMMENT ON COLUMN sample_t.name IS '이름';
COMMENT ON COLUMN sample_t.age IS '나이';
COMMENT ON COLUMN sample_t.gender IS '성별(M:남자, F:여자)';
COMMENT ON COLUMN sample_t.birth_day IS '생년월일';

-- DESC SAMPLE_T
SELECT * FROM USER_ALL_TABLES WHERE TABLE_NAME = 'SAMPLE_T';
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SAMPLE_T';
SELECT * FROM USER_COL_COMMENTS WHERE TABLE_NAME = 'SAMPLE_T';
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'SAMPLE_T';


CREATE TABLE ALT_T (
       u_id NUMBER
     , name VARCHAR(10)
     , g_type CHAR(1)
     , now_date DATE
     , remark VARCHAR(100)
);
CREATE TABLE MY_TEST_REF(
       ref_id NUMBER PRIMARY KEY
     , ref_text VARCHAR(100)
);

ALTER TABLE ALT_T RENAME TO MY_TEST; -- 비추천!

ALTER TABLE MY_TEST RENAME COLUMN now_date TO birth_date;  -- 비추천!
ALTER TABLE MY_TEST ADD age NUMBER(3) DEFAULT(0) NOT NULL;
ALTER TABLE MY_TEST ADD ref_col NUMBER;
ALTER TABLE MY_TEST MODIFY name VARCHAR(50);  -- 데이터의 크기를 늘리는 방향으로 사용하는 것을 추천.
ALTER TABLE MY_TEST DROP COLUMN remark; -- 비추천!

ALTER TABLE MY_TEST MODIFY u_id CONSTRAINT PK_MY_TEST_U_ID PRIMARY KEY; -- 컬럼 레벨로 컬럼 수정하면서 추가
ALTER TABLE MY_TEST ADD CONSTRAINT PK_MY_TEST_U_ID PRIMARY KEY(u_id); -- 테이블 레벨로 추가
ALTER TABLE MY_TEST MODIFY name CONSTRAINT UK_MY_TEST_NAME UNIQUE;
ALTER TABLE MY_TEST ADD CONSTRAINT UK_MY_TEST_NAME UNIQUE(name);
ALTER TABLE MY_TEST MODIFY ref_col CONSTRAINT FK_MY_TEST_REF_COL REFERENCES MY_TEST_REF(ref_id);
ALTER TABLE MY_TEST ADD CONSTRAINT FK_MY_TEST_REF_COL FOREIGN KEY(ref_col) REFERENCES MY_TEST_REF(ref_id);

ALTER TABLE MY_TEST MODIFY g_type CONSTRAINT NN_MY_TEST_G_TYPE NOT NULL;
ALTER TABLE MY_TEST MODIFY age CONSTRAINT CK_MY_TEST_AGE CHECK(AGE BETWEEN 0 AND 150);

ALTER TABLE MY_TEST
       DROP CONSTRAINT PK_MY_TEST_U_ID DROP CONSTRAINT FK_MY_TEST_REF_COL
       DROP CONSTRAINT UK_MY_TEST_NAME DROP CONSTRAINT NN_MY_TEST_G_TYPE
       DROP CONSTRAINT CK_MY_TEST_AGE;
      
      
ALTER TABLE MY_TEST_REF DROP COLUMN ref_id CASCADE CONSTRAINT; -- 비추천...
DROP TABLE MY_TEST_REF CASCADE CONSTRAINT; -- 비추천


SELECT * FROM USER_ALL_TABLES WHERE TABLE_NAME = 'MY_TEST';
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MY_TEST';
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'MY_TEST';




















